### ISSUE TITLE
Add support for using 'tags' to organise and navigate between posts

### ISSUE THREAD

**Issue by frankieroberto** [x-govuk/govuk-eleventy-plugin#113]
The [Becoming a teacher design history](https://bat-design-history.netlify.app), which covers 7 services (depending how you count them) is now old enough and big enough that finding posts can be quite hard.

To resolve this, I’ve [added support for tags](https://github.com/DFE-Digital/bat-design-history/pull/787) - which means there’s now a new [Tags page](https://bat-design-history.netlify.app/tags) as well as pages for individual tags, and links to these from the individual posts.

Getting this to work was more fiddly than I expected, as whilst Eleventy already supports "tags" metadata and creates a collection for each tag, collections are also used for other things, including a special `all` collection, and we were also already (mis?)using tags to group together posts from the different services. You also don't get tag pages by default, but need to set this up.

Now that it’s done though, I think it’s proving to be quite useful, and we’d like to improve it in future by possibly having additional tag pages that are scoped by service (as well as the global ones), and to support tags within the "search" feature at the top. The tag pages are also currently missing pagination controls.

I think this feature would be a good candidate for upstreaming into the `govuk-eleventy-plugin`?

**Comment by paulrobertlloyd** [comment]
Nice!

> Getting this to work was more fiddly than I expected, as whilst Eleventy already supports "tags" metadata and creates a collection for each tag, collections are also used for other things

Its for reasons like this that I’m in the process of moving my own site over to [Lume](https://lume.land), which has taken a far more holistic approach to tagging and pagination, is is far less hacky. `govuk-lume`? Don’t Paul, please don’t. 😂

**Comment by frankieroberto** [comment]
> Its for reasons like this that I’m in the process of moving my own site over to [Lume](https://lume.land), which has taken a far more holistic approach to tagging and pagination, and is far less hacky. `govuk-lume`? Don’t Paul, please don’t. 😂

🤦  I must admit I was kinda surprised that tags were only half a feature in Eleventy, given that it was presumably built for blogging, where tags are quite an old-school feature! (Wordpress and even Moveable Type had em!)
