### ISSUE TITLE
Default tags on pages within a section

### ISSUE THREAD

**Issue by HarryMtds** [x-govuk/govuk-eleventy-plugin#157]
Posts within a section always display the parent tag first. Which feels redundant given the page heading. Is there any way to hide it on this page but keep it available for the tag page? 

<img width="1233" alt="Screenshot 2023-04-19 at 09 51 32" src="https://user-images.githubusercontent.com/73660266/233301081-6858df36-95c8-4b9b-bd5d-c38b1ce7fcf4.png">

**Comment by frankieroberto** [comment]
> Alternative option is to use a separate frontmatter key for ‘user-facing’ tags, and leave `tags` as an internal Eleventy mechanism for collecting posts. This is what I’ve ended up doing on my own site ([example](https://raw.githubusercontent.com/paulrobertlloyd/paulrobertlloyd-content/68f392d516d8bdc5c271deef5879ed51d2bba2fd/articles/2023-04-16-birmingham.markdown)).
> 
> I think Eleventy’s idea for using `tags` to collect posts was an interesting one in theory, but one that often breaks down in practice.

I considered this, but then thought it'd be a bit unintuitive to have to use another label for `tags`, and then you’d also have to add some more setup to create the collections for each tag?

I agree though that the way Eleventy mixes up the tags and collections concept is pretty confusing in practice.
