### ISSUE TITLE
Static pages for open data - an idea and a few questions

### ISSUE THREAD

**Issue by michalporeba** [x-govuk/govuk-eleventy-plugin#166]
Recently, I have been looking at options to present (relatively) short, government related, open datasets in both human readable (Design System) and machine readable (multiple formats) way. I'm looking for something that doesn't require a dedicated service, something simple to host, but also something simple to contribute to. 

## Examples

Here are a few examples with my comments on their respective pros and cons. 

### Government organisations on github

The community section on [government.github.com](https://government.github.com/community/) is based on a dataset which can be updated by creating a pull request to [a yaml file](https://github.com/github/government.github.com/blob/gh-pages/_data/governments.yml). This works well for two level hierarchy where the entities have single attribute - the account name. Anything more might get out of hand very quickly. The website doesn't offer an easy way to process the data automatically, you have to use the raw data file in the github repo. 

### Congress Legislators 

There is [a github repo](https://github.com/unitedstates/congress-legislators) with published data on Congress Legislators (US public sector, but the same principle applies to us) is another example. They have only a github repo with yaml files. There is techy readable but not an average person readable. The files can be consumed by automated processes but only by referencing raw file paths on github. 

### Services list maintained by x-govuk

The x-govuk [list of digital services](https://govuk-digital-services.herokuapp.com/). The simple list of services in Design System is available, some information about what it is, how to contribute is available. Data can be more complex as each entity is in a json file. However, the automated processing is more difficult as multiple files have to be navigated. Replicating this solution for another dataset would require copying a lot of boilerplate code - using eleventy plugin would be a better option. 

## Proposal

I would like to extend the work you have done with govuk-eleventy-plugin and offer a simplified way to create a standard data-product page, a data-collection page and perhaps a data-detail page. I would like to keep the data in [CSVW](https://csvw.org) format which is then automatically translated into static pages with [RDFa annotations](https://en.wikipedia.org/wiki/RDFa) as well as other data formats (e.g. [RDF in Turtle](https://www.w3.org/TR/turtle/), [JSON-LD](https://json-ld.org/))

## Questions

* Would you be open to addition of such templates? 
* I'm happy to do the work, but I will need some support. Would you be happy to offer some guidance regarding eleventy and govuk-eleventy-plugin? Depending on the answer to the first question this might be either to contribute templates within the project or to build a separate plugin that extends govuk-eleventy-plugin.

**Comment by frankieroberto** [comment]
Hi @michalporeba and thanks for dropping by! It sounds like an interesting proposal, but as @paulrobertlloyd it's hard to evaluate without a specific use case in mind.

For the [list of government service](https://govuk-digital-services.herokuapp.com) it made sense to use JSON files partly to make the [contribution process](https://govuk-digital-services.herokuapp.com/contribute) a bit easier (copy and paste a template into a new JSON file, then edit), and also partly to contain more structured information. 

That service actually uses a custom mini Express app rather than a Rails app, which mostly just parses the JSON files into memory and then uses those to render the pages. There's a bit of custom stuff but the basics is pretty simple.

**Comment by frankieroberto** [comment]
@michalporeba do you have any particular first dataset in mind? In my experience it’s easier to go from a few specific instances to a generic design rather than starting with a more generic option.

**Comment by michalporeba** [comment]
@frankieroberto yes, I have a few initial datasets in mind. This is not the problem. At the moment I'm trying to figure out the approach. Whether to use Eleventy, or perhaps mkdocs, or something else. If Eleventy, for example, to what extent should I depend on the govuk-eleventy-plugin or more directly on the protyping kit. And should I create it assuming I will try to contribute it back upstream, or publish it as a new package.

**Comment by paulrobertlloyd** [comment]
Closing. Feel free to reopen if you have further thoughts on this idea and where you feel this plug-in may be able to help.
