### ISSUE TITLE
v5.0.4 release

### ISSUE THREAD

**Issue by frankieroberto** [x-govuk/govuk-eleventy-plugin#191]
@paulrobertlloyd I've merged some dependabot alerts and manually updated some dependencies in order to resolve some security alerts (which are pretty low risk for a static site but annoying nonetheless).

Worth doing a v5.0.4 release for? (This'll also fix any security alerts on downstream sites which use this plugin).

**Comment by paulrobertlloyd** [comment]
[Done!](https://github.com/x-govuk/govuk-eleventy-plugin/releases/tag/v5.0.4)

**Comment by frankieroberto** [comment]
@paulrobertlloyd thanks! Do you have a process for doing the release, generating the release notes, etc, or is it semi-manual? (I should know this stuff but either I've never learnt or I've forgotten)

**Comment by paulrobertlloyd** [comment]
I’ve been using [`np`](https://github.com/sindresorhus/np); perhaps there’s a case for adding it as a dev dependency and adding a script task, or at least adding a note about releasing updates to the `README`.

**Comment by frankieroberto** [comment]
@paulrobertlloyd oh nice! happy to add it as a dev dependency - or just as documentation somewhere if that's easier.

@peteryates has [a neat GitHub action](https://github.com/x-govuk/govuk-components/blob/main/.github/workflows/publish.yml) which auto-publishes to rubygems when there's a new tag – wonder if it's worth doing something similar but for npm?
