### ISSUE TITLE
Getting started deployed page lists no layouts

### ISSUE THREAD

**Issue by stuartlangridge** [x-govuk/govuk-eleventy-plugin#200]
https://x-govuk.github.io/govuk-eleventy-plugin/get-started/ says the following:

![image](https://github.com/x-govuk/govuk-eleventy-plugin/assets/4356350/f32d0452-c69a-4821-83c8-e276b9e32a46)

I'm not sure exactly how this should work, but I feel like it should list some layouts here, rather than "0 layouts".

**Comment by paulrobertlloyd** [comment]
Whoops! Thanks for spotting, now fixed.
