### ISSUE TITLE
Thanks, and a question

### ISSUE THREAD

**Issue by pranaykotas** [x-govuk/govuk-eleventy-plugin#243]
I'm a newbie to Eleventy, trying to use this plugin for a non-profit think tank website. I want to know how you enabled the sticky left-side menu layout as is the case on this gov.uk [page](https://www.gov.uk/government/publications/national-semiconductor-strategy/national-semiconductor-strategy#our-plan-to-safeguard-the-uk-against-supply-chain-disruption-and-build-supply-chain-resilience). Can I implement that feature by configuring options in your plugin?

**Comment by paulrobertlloyd** [comment]
Hi @pranaykotas. This plugin, or Eleventy, wasn’t use to build that page. That’s built using a separate publishing system.

However, this plugin does provide a [sub-navigation layout](https://x-govuk.github.io/govuk-eleventy-plugin/layouts/sub-navigation/) ([example](https://x-govuk.github.io/govuk-eleventy-plugin/example-layouts/sub-navigation/)), which would allow you to achieve a similar design, albeit without the stickiness. The items shown in the sidebar are derived from your site’s navigation (see the [Eleventy navigation plugin docs](https://www.11ty.dev/docs/plugins/navigation/)).

**Comment by paulrobertlloyd** [comment]
Closing. Feel free to reopen if you have any further questions.
