### ISSUE TITLE
Default opengraph image meta tag being added even if a post one is set

### ISSUE THREAD

**Issue by frankieroberto** [x-govuk/govuk-eleventy-plugin#279]
On posts like [this one](https://x-govuk.github.io/posts/introduction/), the following HTML is being rendered in the `<head>`:

```html
<meta property="og:image" content="https://x-govuk.github.io/assets/posts/introduction/x-govuk-logo.png">
<meta property="og:image:alt" content="The GOV.UK crown viewed from above.">
<meta property="og:image" content="https://x-govuk.github.io//images/govuk-opengraph-image.png">
```

The second `og:image` is the default one (`govuk-opengraph-image.png`), which shouldn’t be being rendered at all.

I’d not noticed this before, I guess because most social media platforms will select the first tag if there’s a duplicate, but BlueSky seems to pick the second one.  (Separately, there’s a bug which is that the second default URL contains a double `//` which means it’s broken).

Going to do some investigation into this...

**Comment by paulrobertlloyd** [comment]
Fix pushed in v6.2.5; feel free to close this issue if your change fixes this issue.
