### ISSUE TITLE
Cannot override Nunjucks configuration

### ISSUE THREAD

**Issue by galund** [x-govuk/govuk-eleventy-plugin#291]
The 11ty docs suggest overriding the default Nunjucks configuration with a stanza like

```
eleventyConfig.setNunjucksEnvironmentOptions({
  dev: true
});
```
in `eleventy.config.js`. (This example was to set a flag which I was hoping would tell me what was wrong with my template, ho hum.)

However, the way that the plugin configures Nunjucks in https://github.com/x-govuk/govuk-eleventy-plugin/blob/main/lib/nunjucks.js#L36 this doesn't seem to be possible. A default configuration is obviously essential, but it would be nice if this just worked.

**Comment by paulrobertlloyd** [comment]
Now possible in v6.3.0 of the plugin. Thanks for reporting this issue!
