### ISSUE TITLE
How to remove all GOV.UK branding?

### ISSUE THREAD

**Issue by hickford** [x-govuk/govuk-eleventy-plugin#292]
> You’re welcome to use the plugin even if your service isn’t considered part of GOV.UK, but your site or service must not:
> 
> - identify itself as being part of GOV.UK
> - use the crown or GOV.UK logotype in the header
> - use the GDS Transport typeface
> - suggest that it’s an official UK government website if it’s not

How can I completely remove all GOV.UK branding ? Do you have an example eleventy.config.js?

I tried setting several options from https://x-govuk.github.io/govuk-eleventy-plugin/options/ but the typeface remains GDS Transport and the title element still contains "GOV.UK".

**Comment by paulrobertlloyd** [comment]
Hi @hickford. Perhaps we can add some documentation to make this a bit clearer. In short:

## Change GOV.UK logo in the header

* You can use the `header.logotype.text` option to change this to another value.
* Use `logo.logotype.html` to replace it with your own HTML (which could, for example, contain an SVG logo or an image alongside some text, for example)

## Replace the GDS Transport typeface

This can be achieved by overriding the global SCSS settings for `govuk-frontend`.

Add a `_settings.scss` file to `[input.dir]/sass/` (you can change this location with the `scssSettingsPath` option).

Then in this SCSS file, override `$govuk-font-family` setting:

```scss
$govuk-font-family: Comic Sans, cursive;
```

See all available [global SCSS settings](https://frontend.design-system.service.gov.uk/sass-api-reference/#settings)
