### ISSUE TITLE
Add extra information on adding search

### ISSUE THREAD

**Issue by vickytnz** [x-govuk/govuk-eleventy-plugin#309]
The description on https://x-govuk.github.io/govuk-eleventy-plugin/search/ 

>  ## Create a search index
The site search needs an index of your pages and the key words and phrases they contain.
> Create the search index by creating a page that uses the search-index layout:

The missing context for me was naming it properly - it seems like `search.json.njk` is the one that works properly as it can have unexpected results in other formats?

**Comment by paulrobertlloyd** [comment]
It doesn’t need to be called `search.json.njk`, but it does need to end in `.njk` I think. Have update the instructions to follow the instructions provided for creating an RSS feed, and provided a suggested template name.
