### ISSUE TITLE
Insert internal images 

### ISSUE THREAD

**Issue by SoumayaMauthoorMOJ** [x-govuk/govuk-eleventy-plugin#312]
We use eleventy for our [handbook](https://ministryofjustice.github.io/data-and-analytics-engineering/).

My documentation often references internal images for example:

![image](https://github.com/user-attachments/assets/5ab63c71-80d6-479b-8850-709bd0d0fd79)

In the example above I have tried  to insert the image inline using a relative path `[./images/context-diagram.excalidraw.png]`

This renders correctly in GitHub but not when published to the website. Instead I have to use a raw github link: 
`[https://raw.githubusercontent.com/ministryofjustice/data-and-analytics-engineering/main/src/content/about/images/context-diagram.excalidraw.png]`

How I can insert the image inline so that it renders correctly on both GitHub and the website without using the raw github address?

**Comment by paulrobertlloyd** [comment]
If you use paths that are relative to the markdown file, these should get upgraded to work whether you are viewing locally, or on folder on GitHub Pages.

So, in the above example, the following should work:

```md
![../images/context-diagram.excalidraw.png]
```

(Note that the path begins with two dots, not one). Let me know if this works.

**Comment by SoumayaMauthoorMOJ** [comment]
Hi @paulrobertlloyd thanks for getting back to me! I think the problem is that the images do not get copied over to the build folder:
<img width="346" alt="image" src="https://github.com/user-attachments/assets/53a52a13-7574-4247-9a4c-efd72b797e89">
How can i force eleventy to copy over the images when building the website?

**Comment by paulrobertlloyd** [comment]
Ah! For this you'll need to configure copying assets using [the `addPassthroughCopy` method](https://www.11ty.dev/docs/copy/) in your Eleventy config.

**Comment by SoumayaMauthoorMOJ** [comment]
Thank you!
