### ISSUE TITLE
Subdomains need url variable for site search to work 

### ISSUE THREAD

**Issue by vickytnz** [x-govuk/govuk-eleventy-plugin#323]
Site search did not respect the subdomains until I added url back as a variable.

`url:
      process.env.GITHUB_ACTIONS &&
      'https://vickytnz.github.io/xgov-accessibility/',`

**Comment by paulrobertlloyd** [comment]
Hopefully the fix in bc13140 addresses this; seems to work on the documentation site, but will release an update and we can confirm.
