### ISSUE TITLE
Add timeline

### ISSUE THREAD

**Issue by SoumayaMauthoorMOJ** [x-govuk/govuk-eleventy-plugin#328]
Hello 👋  we use this plugin for our [handbook](https://ministryofjustice.github.io/data-and-analytics-engineering/). Is there an eleventy plugin or open-source library that you can recommend for creating a timeline or roadmap and publishing to your eleventy site?

**Comment by paulrobertlloyd** [comment]
Not that I know of – but you could always create one!

Perhaps start with HTML and maybe a custom component first, and go from there. Maybe you can achieve this with Markdown alone? There’s the [Timeline component](https://design-patterns.service.justice.gov.uk/components/timeline/) you could borrow from, too.

**Comment by SoumayaMauthoorMOJ** [comment]
Thanks @paulrobertlloyd we'll have a look a the timeline component :-)
