### ISSUE TITLE
Missing example tags page

### ISSUE THREAD

**Issue by chrisns** [x-govuk/govuk-eleventy-plugin#334]
re #115 
https://x-govuk.github.io/govuk-eleventy-plugin/tags/example-tag

https://github.com/x-govuk/govuk-eleventy-plugin/pull/115/files#diff-bae99a25c62b34d8da01bf0901142bf312b86508a92efcc4ad1cc044f71250c6R43

refers to https://x-govuk.github.io/govuk-eleventy-plugin/tags/example-tag

which 404s :(

So I'm a bit lost trying to implement (hacky tags)

**Comment by paulrobertlloyd** [comment]
Fixed in fa33ae65a592795b82851271dee31dbcb3c6c39a
